#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "Bhargav Tarpara"
description: "Personal Site"
language: "en"

#url: http://bhargavtarpara.com
#url: https://btruer.github.io
url: http://localhost:4000
baseurl: ''
timezone: America/New_York

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 5
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
disqus-id: bhargavtarpara
enable_disqus: true
enable-share: true
github: btruer


#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
gems: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/
