# Setup
title:               Bhargav Tarpara
tagline:             Bhargav Tarpara's site
url:                 btruer.github.io
analytics_id:

# About/contact
author:
  name:                Bhargav Tarpara
  email:               "bhargavtarpara@yahoo.com" # email here
  avatar:              img/avatar.jpg
  profile-pic:         img/profile-pic.jpg



# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Bhargav Tarpara
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
